language: node_js
node_js:
- 8.9.4
script:
- npm run build
- npm run coverage
after_success:
- codecov
deploy:
  skip_cleanup: true
  provider: npm
  on:
    branch: master
  api_key:
    secure: dh5o8PaSNSDOWAXLpxrcx7sRFmAFt/nCGheDgYJBwkbh+frVQpkxoZP/0p3EceCVomE7LKXTg87EYSGR/PuFbIYysitkhBt4WoOefZkpMRVjs9c8p/5Rha0PRwoB/IGLZvKi0Ct6OcFWfbePolNEgwNSSYs7ooxcULrsmddGCe8dOMYkZBG0h2lEE1ffJg9sRt0jO+gtwgun+RR+jROLLyl/leNzHQCs/P9xyVed5tsPyi/kqBdqLWmzcPaNw/5BbVEKnHsQdKJnv5vIHVDLxabW/S2EV1JYaMF3smEWHWNapZW75qLIXzmvvLfNuKrL6r+k+5Gc73/9SbIAJ7R8C+nM20eZ22OY6o7Uvnw6w42+8eCwWWw0qcQhjIPxyoYK46khE3qrHGQCVw0/xXPfc80yVhe2URH9tAnHZn7dlVZEv121MzwR9FK9SJg1LIaRB69r3pds5jQebljsrStCjMqIdEMEzAgz+tF6Sp+Jgwclfu58qewTLrLWY5hH894BlchBZxOYxQOmBFe9g6VVnGWFE+qAC/bM9Y1os0AsYr8nHlEFpsHjysxIOdV9RVu/+jVB2GPtQuAdeizVPgwG1LdIC/q+7qNWYvmbo71onCrgKCapP4kwxS1is4mUFCo/3iPhqN33OXCQI24mY22OVWun82w9AdML9CQz8yJjAio=
